<b>Description:</b>
-

### Import Python libraries and user-defined modules

In [1]:
#from dotenv import load_dotenv
import pandas as pd
import data_profiling
from data_profiling import ProfileReport

In [30]:
#import prep.preprocessing as prep

In [32]:
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [45]:
#import os
#os.getcwd()

In [33]:
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\o.hamed\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\o.hamed\AppData\Roaming\nltk_data...
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\o.hamed\AppData\Roaming\nltk_data...

True

### Load variables from .env file

In [17]:
#load_dotenv()

XLSX_FILES_FOLDER = "../data/xlsx"
HTML_REPORTS_FOLDER = "../reports"

XLSX_FILES_FOLDER, HTML_REPORTS_FOLDER

('../data/xlsx', '../reports')

### Read the dataset and high-level EDA

In [46]:
#df = read_excel_files(XLSX_FILES_FOLDER, pattern, debug=True)
df= pd.read_excel(XLSX_FILES_FOLDER+"/image_metadata.xlsx", sheet_name="Sheet1")

In [47]:
stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

def preprocess(text):

    text = text.lower()

    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'@\w+', '', text)
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'\d+', '', text)

    tokens = text.split()

    tokens = [
        lemmatizer.lemmatize(w)
        for w in tokens
        if w not in stop_words and len(w) > 2
    ]

    return " ".join(tokens)

In [51]:
#df.shape ##(502, 9)
df["caption_clean"] = df["caption"].apply(preprocess)

In [52]:
df.head()

,project_id,category,image_id,caption,caption_ai,caption_clean
0,212,Reflector,20180105_101214,a large stainless steel disc with a milled sur...,NaN,large stainless steel disc milled surface
1,212,Reflector,20180105_101224,a rectangular steel plate,NaN,rectangular steel plate
2,212,Reflector,20180302_135657,"Housing of the beryllium reflector, clamped wi...",NaN,housing beryllium reflector clamped six black ...
3,212,Reflector,20180302_135706,"Housing of the beryllium reflector, clamped wi...",NaN,housing beryllium reflector clamped six black ...
4,212,Reflector,20180418-Vortest-1,Mounted housing of the beryllium reflector on ...,NaN,mounted housing beryllium reflector traversing...

In [53]:
col_to_drop = "caption_ai"
df_ic = None
if col_to_drop in df.columns:
    df_ic = df.drop(columns=[col_to_drop])
df_ic.head()

,project_id,category,image_id,caption,caption_clean
0,212,Reflector,20180105_101214,a large stainless steel disc with a milled sur...,large stainless steel disc milled surface
1,212,Reflector,20180105_101224,a rectangular steel plate,rectangular steel plate
2,212,Reflector,20180302_135657,"Housing of the beryllium reflector, clamped wi...",housing beryllium reflector clamped six black ...
3,212,Reflector,20180302_135706,"Housing of the beryllium reflector, clamped wi...",housing beryllium reflector clamped six black ...
4,212,Reflector,20180418-Vortest-1,Mounted housing of the beryllium reflector on ...,mounted housing beryllium reflector traversing...

In [55]:
#df_ic.info()

### Generate Reports using YData/YData-SDK Profiling

In [56]:
import time

In [57]:
start = time.time()
title = "IC for Archive Projects-ITE"

#profile = ProfileReport(df_ic, title=f"{title}", minimal=False, correlations={"pearson": {"calculate": True}, "spearman": {"calculate": True}})
profile = ProfileReport(df_ic, title=f"{title}")

out_html = HTML_REPORTS_FOLDER + f"/{title}.html"
profile.to_file(out_html)

end = time.time()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 52.35it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [58]:
minutes = (end - start) / 60
print(f"Report generated in {minutes:.2f} minutes")

Report generated in 0.14 minutes